//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ATSEntities : DbContext
    {
        public ATSEntities()
            : base("name=ATSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationMenu> ApplicationMenus { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeGlobal> EmployeeGlobals { get; set; }
        public virtual DbSet<Leave> Leaves { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<OrganizationType> OrganizationTypes { get; set; }
        public virtual DbSet<Reason> Reasons { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleMapping> RoleMappings { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Room_TerminalMapping> Room_TerminalMapping { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<Segment> Segments { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<TerminalMaster> TerminalMasters { get; set; }
        public virtual DbSet<TrainingEmployee> TrainingEmployees { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    
        public virtual int USP_IMPORT_GLOBALEMPLOYEE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_IMPORT_GLOBALEMPLOYEE");
        }
    
        public virtual int USP_IMPORT_LOCALEMPLOYEE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_IMPORT_LOCALEMPLOYEE");
        }
    
        public virtual int USP_IMPORT_TIME(string swipeDate)
        {
            var swipeDateParameter = swipeDate != null ?
                new ObjectParameter("SwipeDate", swipeDate) :
                new ObjectParameter("SwipeDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_IMPORT_TIME", swipeDateParameter);
        }
    
        public virtual int USP_IMPORT_TRAININGBASICDATA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_IMPORT_TRAININGBASICDATA");
        }
    }
}
