//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Attendances = new HashSet<Attendance>();
            this.Leaves = new HashSet<Leave>();
            this.TrainingEmployees = new HashSet<TrainingEmployee>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public string EmployeeID { get; set; }
        public Nullable<int> GlobalID { get; set; }
        public Nullable<int> CardID { get; set; }
        public string EmailAddress { get; set; }
        public string NTID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string OrganizationName { get; set; }
        public string Supervisor { get; set; }
        public string Initiator { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual EmployeeGlobal EmployeeGlobal { get; set; }
        public virtual ICollection<Leave> Leaves { get; set; }
        public virtual ICollection<TrainingEmployee> TrainingEmployees { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
