//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeGlobal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeGlobal()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int GlobalID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public string LegalEntity { get; set; }
        public string EmpStatus { get; set; }
        public string EmpType { get; set; }
        public string Initiator { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int Supervisor { get; set; }
        public string EmailAddress { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
