//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public System.Guid LeaveID { get; set; }
        public System.Guid SegmentID { get; set; }
        public string EmployeeID { get; set; }
        public System.Guid ReasonID { get; set; }
        public string Remark { get; set; }
        public string Initiator { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Segment Segment { get; set; }
        public virtual Reason Reason { get; set; }
    }
}
