//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationType
    {
        public OrganizationType()
        {
            this.Organizations = new HashSet<Organization>();
        }
    
        public int TypeID { get; set; }
        public string TypeName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Organization> Organizations { get; set; }
    }
}
