//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.EmployeeGlobals = new HashSet<EmployeeGlobal>();
        }
    
        public int OrganizationID { get; set; }
        public string OrganizationName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<EmployeeGlobal> EmployeeGlobals { get; set; }
        public virtual OrganizationType OrganizationType { get; set; }
    }
}
