//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reason
    {
        public Reason()
        {
            this.Leaves = new HashSet<Leave>();
        }
    
        public System.Guid ReasonID { get; set; }
        public string Name { get; set; }
        public string Initiator { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Leave> Leaves { get; set; }
    }
}
