//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.Schedules = new HashSet<Schedule>();
        }
    
        public System.Guid TeacherID { get; set; }
        public string Name { get; set; }
        public bool IsExternal { get; set; }
        public string Email { get; set; }
        public string Initiator { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EmlpoyeeID { get; set; }
    
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
