//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalMaster
    {
        public TerminalMaster()
        {
            this.Room_TerminalMapping = new HashSet<Room_TerminalMapping>();
        }
    
        public System.Guid TerminalID { get; set; }
        public string Name { get; set; }
        public string Initiator { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Room_TerminalMapping> Room_TerminalMapping { get; set; }
    }
}
