//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingEmployee
    {
        public System.Guid ID { get; set; }
        public int ScheduleID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<System.DateTime> StopFrom { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
