//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public System.Guid TransactionID { get; set; }
        public string EmployeeID { get; set; }
        public string CardID { get; set; }
        public System.DateTime Time { get; set; }
        public System.Guid RoomID { get; set; }
        public bool InOut { get; set; }
    }
}
